#!/usr/bin/env python3
"""Generate report/harness_report.pdf - a slide-style deck of harness results.

Structure: cover, setup, leaderboard, cost scatter, then an ABLATION LADDER -
four one-factor upgrades (1-turn -> harness, low -> medium effort, blind ->
visual, v1 -> v2), each with a side-by-side metric table and a case study
showing the agent's reasoning per iteration. Everything is pulled
programmatically from runs/. Rerun: ~/mamba/envs/lathe/bin/python make_report.py
"""

from __future__ import annotations

import json
import re
import statistics
from datetime import date
from pathlib import Path

import fitz
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas

from make_results import CORE, METRICS, agg, load_methods, split_method

HERE = Path(__file__).resolve().parent
OUT = HERE / "report" / "harness_report.pdf"
PAGE_W, PAGE_H = landscape(A4)

NAVY = colors.HexColor("#14243b")
BLUE = colors.HexColor("#3267a8")
TEAL = colors.HexColor("#168a72")
AMBER = colors.HexColor("#d38a22")
RED = colors.HexColor("#c74747")
LIGHT = colors.HexColor("#f4f6f8")
MID = colors.HexColor("#d9dfe7")
TEXT = colors.HexColor("#1f2933")
MUTED = colors.HexColor("#5c6773")

ASCII = {"👁": "visual", "✗": "blind", "⚡": "low", "⚡⚡": "medium", "⚡⚡⚡": "high"}

# ----- the ablation ladder: each step changes exactly one factor -------------
LADDER = [
    {
        "title": "Upgrade 1: one-shot prompt -> agentic harness",
        "before": "claude opus 1-turn (effort low)",
        "after": "claude opus agentic (novisual, effort low)",
        "changes": "Same model (opus-4.7), same low effort, still no images. The only change: "
                   "instead of one prompt -> one answer, the model gets a workdir with main.tex, "
                   "./score.sh (compile + official metrics), and freedom to edit-score-edit under "
                   "a $3 cap. Feedback is numeric only (blind).",
    },
    {
        "title": "Upgrade 2: reasoning effort low -> medium",
        "before": "claude opus agentic (novisual, effort low)",
        "after": "claude opus agentic (novisual, effort medium)",
        "changes": "Identical harness, identical blind feedback. Only the CLI --effort flag "
                   "changes, giving the model a larger thinking budget per turn.",
    },
    {
        "title": "Upgrade 3: blind -> visual feedback",
        "before": "claude opus agentic (novisual, effort medium)",
        "after": "claude opus agentic (visual, effort medium)",
        "changes": "Same model, effort, harness. The agent may now Read reference page PNGs and "
                   "the labeled diff images (red = missing, blue = extra, yellow/orange = "
                   "displaced) regenerated by every score run.",
    },
    {
        "title": "Upgrade 4: harness v1 -> v2 tooling",
        "before": "claude opus agentic (visual, effort medium)",
        "after": "claude opus agentic (visual, effort medium) [v2]",
        "changes": "Same model, effort, visual feedback. v2 adds: best-so-far auto-checkpoint "
                   "(regressions become free); ./sweep.sh deterministic grid search over "
                   "typst --input values; fine-grained per-component AND per-page score report; "
                   "registered-raster diagnostic (separates misalignment from the font floor).",
    },
    {
        "title": "Upgrade 5: harness v2 -> v3 (fix the mid-run reward)",
        "before": "claude opus agentic (visual, effort medium) [v2]",
        "after": "claude opus agentic (visual, effort medium) [v3]",
        "changes": "Same model, effort, visual feedback, and v2 tooling. One change: the score the "
                   "agent sees MID-RUN now uses raster_v0.2 (tolerant ink F1 + edge distance) - "
                   "the same number as final grading - instead of v0.1's harsh raster whose "
                   "~25-30 ceiling made real improvements invisible mid-run. The agent stops "
                   "wasting budget chasing a dead component and optimizes what actually moves.",
    },
]


# ---------------------------------------------------------------- utilities
def wrap(pdf, text, x, y, width, size=10, leading=13.5, color=TEXT, font="Helvetica"):
    import textwrap
    pdf.setFont(font, size)
    pdf.setFillColor(color)
    max_chars = max(20, int(width / (size * 0.52)))
    for para in text.split("\n"):
        for line in textwrap.wrap(para, max_chars, break_long_words=False) or [""]:
            pdf.drawString(x, y, line)
            y -= leading
        y -= leading * 0.2
    return y


def header(pdf, title, subtitle=""):
    pdf.setFillColor(NAVY)
    pdf.rect(0, PAGE_H - 46, PAGE_W, 46, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 16)
    pdf.drawString(30, PAGE_H - 30, title)
    if subtitle:
        pdf.setFont("Helvetica", 9)
        pdf.setFillColor(colors.HexColor("#d6e0eb"))
        pdf.drawRightString(PAGE_W - 30, PAGE_H - 29, subtitle)


def footer(pdf, n):
    pdf.setStrokeColor(MID)
    pdf.line(30, 22, PAGE_W - 30, 22)
    pdf.setFillColor(MUTED)
    pdf.setFont("Helvetica", 7.5)
    pdf.drawString(30, 11, "Lathe harness baseline - agentic LaTeX->Typst conversion - development data")
    pdf.drawRightString(PAGE_W - 30, 11, str(n))


def img_fit(pdf, path, x, y, w, h, border=True):
    from PIL import Image
    with Image.open(path) as im:
        r = min(w / im.width, h / im.height)
        dw, dh = im.width * r, im.height * r
    pdf.drawImage(ImageReader(str(path)), x + (w - dw) / 2, y + (h - dh) / 2, dw, dh)
    if border:
        pdf.setStrokeColor(MID)
        pdf.rect(x, y, w, h, stroke=1, fill=0)


def score_color(v):
    return TEAL if v >= 0.7 else AMBER if v >= 0.5 else RED


def method_label(method: str) -> str:
    model, effort, feedback, harness = split_method(method)
    parts = [model, ASCII.get(effort, effort)]
    parts.append(ASCII.get(feedback, feedback))
    if harness != "—":
        parts.append(harness)
    return " / ".join(parts)


def run_index() -> dict[tuple[str, str], Path]:
    """(method, sample_id) -> run dir (newest wins)."""
    idx = {}
    for sp in sorted((HERE / "runs").glob("*/summary.json")):
        d = json.loads(sp.read_text())
        idx[(d.get("method", ""), d["sample_id"])] = sp.parent
    return idx


# ---------------------------------------------------------------- transcript
def trajectory(transcript: Path) -> list[dict]:
    """Score checkpoints; each carries the agent's last reasoning text and last edit."""
    steps, edits, reads = [], 0, 0
    last_text, last_edit = "", ""
    for line in transcript.read_text().splitlines():
        try:
            e = json.loads(line)
        except json.JSONDecodeError:
            continue
        if e.get("type") == "assistant":
            for b in e.get("message", {}).get("content", []):
                if b.get("type") == "tool_use":
                    inp = b.get("input", {})
                    if b["name"] in ("Edit", "Write", "MultiEdit"):
                        edits += 1
                        snip = re.sub(r"\s+", " ", str(inp.get("new_string", inp.get("content", ""))))[:80]
                        if snip:
                            last_edit = f"{b['name'].lower()}: \u201c{snip}\u201d"
                    elif b["name"] in ("Read", "Grep"):
                        reads += 1
                elif b.get("type") in ("text", "thinking"):
                    t = re.sub(r"\s+", " ", str(b.get("text") or b.get("thinking") or "").strip())
                    if t:
                        last_text = t
        elif e.get("type") == "user":
            for b in e.get("message", {}).get("content", []) or []:
                if isinstance(b, dict) and b.get("type") == "tool_result":
                    c = b.get("content")
                    if isinstance(c, list):
                        c = " ".join(str(x.get("text", "")) for x in c if isinstance(x, dict))
                    m = re.search(r"overall=([\d.]+)", str(c))
                    if m:
                        steps.append({"overall": float(m.group(1)), "edits": edits, "reads": reads,
                                      "reasoning": last_text, "edit": last_edit})
                        edits = reads = 0
                        last_text, last_edit = "", ""
    return steps


def render_pdf_page(pdf_path: Path, out_png: Path, page=0, dpi=110):
    doc = fitz.open(pdf_path)
    doc[min(page, doc.page_count - 1)].get_pixmap(dpi=dpi).save(out_png)
    return out_png


# ---------------------------------------------------------------- intro pages
def cover(pdf, methods, spend):
    pdf.setFillColor(NAVY)
    pdf.rect(0, 0, PAGE_W, PAGE_H, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 30)
    pdf.drawString(50, PAGE_H - 100, "Beyond one shot:")
    pdf.drawString(50, PAGE_H - 138, "agentic LaTeX \u2192 Typst conversion")
    pdf.setFont("Helvetica", 14)
    pdf.setFillColor(colors.HexColor("#b9cbe0"))
    pdf.drawString(50, PAGE_H - 172, "Four one-factor upgrades, ablated on the 6 hardest lathe benchmark samples")
    rows = agg(methods, CORE)
    base = rows.get("gemini-3.1-flash-lite (1-turn cascade)", {}).get("overall")
    best_v = max(r["overall"] for r in rows.values()
                 if r["overall"] and r["n_scored"] == r["n_total"])
    pdf.setFillColor(colors.HexColor("#1c3554"))
    pdf.roundRect(50, PAGE_H - 360, PAGE_W - 100, 140, 10, stroke=0, fill=1)
    stats = [
        (f"{100 * base:.0f} \u2192 {100 * best_v:.0f}", "mean overall fidelity, 1-shot baseline vs best method (core 6)"),
        (f"${spend:.0f}", "total tracked API spend"),
        (f"{sum(1 for _ in (HERE / 'runs').glob('*/summary.json'))}", "runs completed"),
    ]
    cw = (PAGE_W - 140) / 3
    for i, (big, small) in enumerate(stats):
        x = 70 + i * cw
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 30)
        pdf.drawString(x, PAGE_H - 285, big)
        wrap(pdf, small, x, PAGE_H - 310, cw - 24, 9, 12, colors.HexColor("#b9cbe0"))
    pdf.setFont("Helvetica", 9)
    pdf.setFillColor(colors.HexColor("#91a8c2"))
    pdf.drawString(50, 40, f"{date.today().isoformat()}  -  harness_baseline/  -  metric pdf_fidelity_v0.1 (deterministic)")
    pdf.showPage()


def setup_page(pdf, n):
    header(pdf, "Setup - task, metric, and gates")
    x = 40
    col_w = (PAGE_W - 2 * x - 24) / 2
    y = PAGE_H - 70
    blocks_left = [
        ("Task set", "The 6 hardest of 157 benchmark samples (one-shot LLM overall 31-38/100): "
         "four table documents that reflow to the wrong page count, one algorithm block, one "
         "figure+caption page. Reference = pdfLaTeX render."),
        ("Score (deterministic, 0-100)", "overall = content^0.35 x visual^0.65; visual = "
         "pagination^0.10 x layout^0.40 x typography^0.20 x raster^0.30. Raster uses the "
         "raster_v0.2 rescoring (tolerant ink F1 + edge distance) which removes v0.1's "
         "~25-30 harshness ceiling; identity still scores 100 and orderings are preserved."),
    ]
    blocks_right = [
        ("Pass gates (frozen before running)", "G1 compiles - G2 page count and pagination "
         "perfect - G3 token precision AND recall >= 0.95 - G4 layout >= 75."),
        ("How to read this deck", "Each following section changes exactly ONE factor "
         "(prompt->harness, effort, visual feedback, tooling) and shows the same table: "
         "per-metric means over the core 6, cost, duration, iterations - then a case study "
         "with the agent's own reasoning per scoring iteration."),
    ]
    for cx, blocks in ((x, blocks_left), (x + col_w + 24, blocks_right)):
        yy = y
        for title, body in blocks:
            pdf.setFillColor(LIGHT)
            pdf.roundRect(cx, yy - 132, col_w, 132, 8, stroke=0, fill=1)
            pdf.setFillColor(BLUE)
            pdf.setFont("Helvetica-Bold", 12)
            pdf.drawString(cx + 14, yy - 24, title)
            wrap(pdf, body, cx + 14, yy - 44, col_w - 28, 9.5, 12.5)
            yy -= 148
    footer(pdf, n)
    pdf.showPage()


def leaderboard(pdf, methods, n):
    header(pdf, "Leaderboard - core 6 hardest samples", "all metrics 0-100; mean over samples")
    rows = agg(methods, CORE)
    ordered = sorted(rows.items(), key=lambda kv: -(kv[1]["overall"] or 0))
    x, y = 40, PAGE_H - 78
    headers = ["model", "effort", "feedback", "harness", "overall", "content", "layout", "typo",
               "raster", "pagin.", "pass", "$/run"]
    widths = [110, 52, 56, 48, 56, 50, 50, 50, 50, 50, 44, 44]
    pdf.setFillColor(NAVY)
    pdf.rect(x, y - 20, sum(widths), 20, stroke=0, fill=1)
    cx = x
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 8.5)
    for h, w in zip(headers, widths):
        pdf.drawString(cx + 5, y - 14, h)
        cx += w
    y -= 20
    for i, (method, r) in enumerate(ordered):
        model, effort, feedback, harness = split_method(method)
        partial = r["n_scored"] < r["n_total"]
        pdf.setFillColor(colors.white if i % 2 == 0 else LIGHT)
        pdf.rect(x, y - 22, sum(widths), 22, stroke=0, fill=1)
        vals = [model, ASCII.get(effort, effort), ASCII.get(feedback, feedback), harness]
        vals += [("(%.1f)" if partial else "%.1f") % (100 * r[k]) if r[k] is not None else "nc"
                 for k in METRICS]
        vals += [f"{r['n_pass']}/{r['n_done']}", f"{r['cost']:.2f}" if r["cost"] else "-"]
        cx = x
        for j, (v, w) in enumerate(zip(vals, widths)):
            if j == 4 and r["overall"] is not None:
                pdf.setFillColor(score_color(r["overall"]))
                pdf.setFont("Helvetica-Bold", 9)
            else:
                pdf.setFillColor(TEXT)
                pdf.setFont("Helvetica-Bold" if j == 0 else "Helvetica", 8)
            pdf.drawString(cx + 5, y - 15, str(v))
            cx += w
        y -= 22
    wrap(pdf, "Parenthesized = partial coverage (queues still running). The four highlighted "
         "one-factor steps from the bottom of this table to the top are ablated in the "
         "following sections.", x, y - 12, PAGE_W - 2 * x, 9, 12, MUTED)
    footer(pdf, n)
    pdf.showPage()


def scatter_page(pdf, n):
    header(pdf, "Cost vs score", "one point per (sample, run)")
    plot = HERE / "plots" / "cost_vs_overall.png"
    if plot.exists():
        img_fit(pdf, plot, 60, 60, PAGE_W - 320, PAGE_H - 140, border=False)
    wrap(pdf, "Reading the plot:\n\n"
         "- One-shot points (bottom-left, dashed gemini line) cluster at 32-52 regardless of model.\n\n"
         "- Best value sits at $0.5-1.0 per document.\n\n"
         "- Spending to the $3 cap does not buy score: those points are budget-cap grinders "
         "oscillating around a plateau.\n\n"
         "- Implication: feedback loop >> model scale >> raw budget.",
         PAGE_W - 240, PAGE_H - 90, 210, 9.5, 13)
    footer(pdf, n)
    pdf.showPage()


# ---------------------------------------------------------------- ablations
COMPARE_COLS = [("overall", "overall"), ("content", "content"), ("layout", "layout"),
                ("typography", "typo"), ("raster", "raster"), ("pagination", "pagin.")]


def ablation_table(pdf, methods, before, after, x, y):
    rows = agg(methods, CORE)
    rb, ra = rows.get(before), rows.get(after)
    headers = [""] + [c[1] for c in COMPARE_COLS] + ["pass", "$/run", "min/run", "iters"]
    widths = [200] + [52] * len(COMPARE_COLS) + [46, 48, 52, 42]
    pdf.setFillColor(NAVY)
    pdf.rect(x, y - 20, sum(widths), 20, stroke=0, fill=1)
    cx = x
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 8.5)
    for h, w in zip(headers, widths):
        pdf.drawString(cx + 5, y - 14, h)
        cx += w
    y -= 20

    def fmt_row(label, r, shade):
        nonlocal y
        pdf.setFillColor(shade)
        pdf.rect(x, y - 22, sum(widths), 22, stroke=0, fill=1)
        vals = [label]
        if r:
            partial = r["n_scored"] < r["n_total"]
            vals += [("(%.1f)" if partial else "%.1f") % (100 * r[k]) if r[k] is not None else "nc"
                     for k, _ in COMPARE_COLS]
            vals += [f"{r['n_pass']}/{r['n_done']}", f"{r['cost']:.2f}" if r["cost"] else "-",
                     f"{r['time']/60:.1f}" if r["time"] else "-",
                     f"{r['iters']:.0f}" if r["iters"] else "-"]
        else:
            vals += ["-"] * (len(COMPARE_COLS) + 4)
        cx2 = x
        for j, (v, w) in enumerate(zip(vals, widths)):
            pdf.setFillColor(TEXT)
            pdf.setFont("Helvetica-Bold" if j == 0 else "Helvetica", 8)
            pdf.drawString(cx2 + 5, y - 15, str(v))
            cx2 += w
        y -= 22

    fmt_row("BEFORE  " + method_label(before), rb, colors.white)
    fmt_row("AFTER   " + method_label(after), ra, LIGHT)
    # delta row
    if rb and ra:
        pdf.setFillColor(colors.HexColor("#eaf5f1"))
        pdf.rect(x, y - 22, sum(widths), 22, stroke=0, fill=1)
        cx2 = x
        deltas = ["\u0394"]
        for k, _ in COMPARE_COLS:
            if rb[k] is not None and ra[k] is not None:
                deltas.append(f"{100 * (ra[k] - rb[k]):+.1f}")
            else:
                deltas.append("-")
        deltas += [f"{ra['n_pass'] - rb['n_pass']:+d}",
                   f"{(ra['cost'] or 0) - (rb['cost'] or 0):+.2f}" if ra["cost"] and rb["cost"] else "-",
                   "-", "-"]
        for j, (v, w) in enumerate(zip(deltas, widths)):
            good = j > 0 and str(v).startswith("+")
            pdf.setFillColor(TEAL if good else RED if str(v).startswith("-") and v != "-" else MUTED)
            pdf.setFont("Helvetica-Bold", 8)
            pdf.drawString(cx2 + 5, y - 15, str(v))
            cx2 += w
        y -= 22
    return y


def per_sample_deltas(pdf, methods, before, after, x, y):
    mb, ma = methods.get(before, {}), methods.get(after, {})
    pdf.setFont("Helvetica-Bold", 10)
    pdf.setFillColor(TEXT)
    pdf.drawString(x, y, "Per-sample overall (before -> after):")
    y -= 16
    for s in CORE:
        eb, ea = mb.get(s), ma.get(s)
        vb = 100 * eb["overall"] if eb and not eb.get("failed_compile") else None
        va = 100 * ea["overall"] if ea and not ea.get("failed_compile") else None
        txt = f"{s}:  "
        txt += f"{vb:.1f}" if vb is not None else "nc/-"
        txt += " -> "
        txt += f"{va:.1f}" if va is not None else "nc/-"
        if vb is not None and va is not None:
            txt += f"  ({va - vb:+.1f})"
            col = TEAL if va > vb else RED
        else:
            col = MUTED
        pdf.setFont("Helvetica", 8.5)
        pdf.setFillColor(col)
        pdf.drawString(x + 8, y, txt)
        y -= 13
    return y


def pick_ablation_case(methods, idx, before, after) -> str | None:
    """Largest-gain sample; prefer ones whose AFTER run has a step transcript."""
    mb, ma = methods.get(before, {}), methods.get(after, {})
    candidates = []
    for s in CORE:
        eb, ea = mb.get(s), ma.get(s)
        if not (eb and ea) or eb.get("failed_compile") or ea.get("failed_compile"):
            continue
        run_dir = idx.get((after, s))
        has_transcript = bool(run_dir and (run_dir / "claude_transcript.jsonl").exists())
        candidates.append((has_transcript, ea["overall"] - eb["overall"], s))
    if not candidates:
        return None
    return max(candidates)[2]


def ablation_pages(pdf, methods, idx, step, n):
    before, after = step["before"], step["after"]
    header(pdf, step["title"])
    x, y = 40, PAGE_H - 66
    pdf.setFillColor(LIGHT)
    pdf.roundRect(x, y - 58, PAGE_W - 2 * x, 58, 8, stroke=0, fill=1)
    pdf.setFillColor(BLUE)
    pdf.setFont("Helvetica-Bold", 10)
    pdf.drawString(x + 12, y - 16, "What changed in this step")
    wrap(pdf, step["changes"], x + 12, y - 30, PAGE_W - 2 * x - 24, 9, 11.5)
    y -= 76
    y = ablation_table(pdf, methods, before, after, x, y)
    y -= 20
    y = per_sample_deltas(pdf, methods, before, after, x, y)
    footer(pdf, n)
    pdf.showPage()
    n += 1

    # case study page: sample with the largest gain for this upgrade
    sample = pick_ablation_case(methods, idx, before, after)
    if not sample:
        return n
    eb, ea = methods[before][sample], methods[after][sample]
    header(pdf, f"{step['title']} - case: {sample}",
           f"overall {100 * eb['overall']:.1f} -> {100 * ea['overall']:.1f}")
    x, y = 40, PAGE_H - 70

    # metric side-by-side for this sample (proper columns, not space-padded text)
    label_w, col_w = 250, 56
    total_w = label_w + col_w * len(COMPARE_COLS)
    pdf.setFillColor(NAVY)
    pdf.rect(x, y - 18, total_w, 18, stroke=0, fill=1)
    pdf.setFillColor(colors.white)
    pdf.setFont("Helvetica-Bold", 8.5)
    for j, (_, lbl) in enumerate(COMPARE_COLS):
        pdf.drawRightString(x + label_w + (j + 1) * col_w - 8, y - 13, lbl)
    y -= 18
    for shade, label, method, e in ((colors.white, "BEFORE", before, eb),
                                    (LIGHT, "AFTER", after, ea)):
        pdf.setFillColor(shade)
        pdf.rect(x, y - 20, total_w, 20, stroke=0, fill=1)
        pdf.setFillColor(MUTED if label == "BEFORE" else TEAL)
        pdf.setFont("Helvetica-Bold", 8.5)
        pdf.drawString(x + 6, y - 14, f"{label}  {method_label(method)}")
        pdf.setFont("Helvetica", 9)
        for j, (k, _) in enumerate(COMPARE_COLS):
            pdf.drawRightString(x + label_w + (j + 1) * col_w - 8, y - 14, f"{100 * e[k]:.1f}")
        y -= 20
    y -= 20

    # reasoning log of the AFTER run
    run_dir = idx.get((after, sample)) or idx.get((after.replace(" [v2]", ""), sample))
    steps = []
    if run_dir and (run_dir / "claude_transcript.jsonl").exists():
        steps = trajectory(run_dir / "claude_transcript.jsonl")
    if steps:
        pdf.setFont("Helvetica-Bold", 10)
        pdf.setFillColor(TEXT)
        pdf.drawString(x, y, f"AFTER run, iteration by iteration ({method_label(after)}):")
        y -= 16
        pdf.setFont("Helvetica-Bold", 7.5)
        pdf.setFillColor(MUTED)
        pdf.drawString(x, y, "iter   overall   \u0394        agent's reasoning before this score run  /  last edit")
        y -= 12
        for i, s in enumerate(steps, 1):
            if y < 40:
                break
            delta = s["overall"] - steps[i - 2]["overall"] if i > 1 else None
            col = TEAL if (delta or 0) > 0.3 else RED if (delta or 0) < -0.3 else MUTED
            pdf.setFillColor(col)
            pdf.setFont("Helvetica-Bold", 8)
            d_txt = f"{delta:+.1f}" if delta is not None else "start"
            pdf.drawString(x, y, f"#{i:02d}  {s['overall']:5.1f}  {d_txt:>7}")
            note = s["reasoning"] or s["edit"] or f"{s['edits']} edit(s) before scoring"
            pdf.setFillColor(TEXT)
            pdf.setFont("Helvetica", 7.5)
            pdf.drawString(x + 118, y, note[:165])
            if s["reasoning"] and s["edit"] and y > 50:
                y -= 10
                pdf.setFillColor(MUTED)
                pdf.drawString(x + 118, y, s["edit"][:165])
            y -= 13
    else:
        wrap(pdf, "No transcript for the AFTER run (older run without step logging).", x, y, 500, 9)
    footer(pdf, n)
    pdf.showPage()
    return n + 1


def final_render_page(pdf, methods, idx, n):
    """Best graded conversion: reference vs candidate render."""
    best = None
    for (method, sample), run_dir in idx.items():
        sp = run_dir / "summary.json"
        d = json.loads(sp.read_text())
        f = d.get("final")
        if f and f.get("compiled") and (best is None or f["overall"] > best[0]):
            best = (f["overall"], method, sample, run_dir)
    if not best:
        return n
    overall, method, sample, run_dir = best
    header(pdf, f"Best conversion so far: {sample}",
           f"{method_label(method)} - overall {100 * overall:.1f}")
    tmp = HERE / "report"
    panels = [("Reference (pdfLaTeX)", render_pdf_page(run_dir / "work" / "reference.pdf", tmp / "best_ref.png"))]
    cand = run_dir / "final_candidate.pdf"
    if cand.exists():
        panels.append(("Final candidate (Typst)", render_pdf_page(cand, tmp / "best_cand.png")))
    diff = run_dir / "final_diagnostics" / "diff_p1.png"
    if diff.exists():
        panels.append(("Raster diff (red=missing, blue=extra)", diff))
    pw = (PAGE_W - 80 - 20 * (len(panels) - 1)) / len(panels)
    for i, (label, path) in enumerate(panels):
        px = 40 + i * (pw + 20)
        pdf.setFillColor(NAVY)
        pdf.roundRect(px, PAGE_H - 92, pw, 18, 3, stroke=0, fill=1)
        pdf.setFillColor(colors.white)
        pdf.setFont("Helvetica-Bold", 8.5)
        pdf.drawString(px + 6, PAGE_H - 87, label)
        img_fit(pdf, path, px, 40, pw, PAGE_H - 140)
    footer(pdf, n)
    pdf.showPage()
    return n + 1


def findings(pdf, n):
    header(pdf, "Findings and next steps")
    x = 40
    col_w = (PAGE_W - 2 * x - 24) / 2
    y = PAGE_H - 70
    left = [
        ("Which upgrades pay", "1-turn -> harness is the big one (+~20 overall; page counts fixed "
         "everywhere). Visual feedback and v2 tooling each add several points; extra effort mainly "
         "buys reliability, not peak score. Model scale alone changes almost nothing at 1 turn."),
        ("Where it saturates", "Raster sits at its font floor (~20-30); late iterations oscillate "
         "by ~1 point. 05_tables_simple_021 resists all variants so far."),
    ]
    right = [
        ("v2 tooling", "Checkpointing makes bad experiments free; the deterministic sweep found "
         "margins/spacing the LLM had hand-nudged for 15 turns - runs that used it posted the two "
         "best scores of the experiment."),
        ("Next", "v2.1 prompt: always sweep before manual nudges, keep iterating while under "
         "budget. Repeat runs for noise; human-calibrate metric weights; then RL hill-climbing "
         "with the same deterministic reward."),
    ]
    for cx, blocks in ((x, left), (x + col_w + 24, right)):
        yy = y
        for title, body in blocks:
            pdf.setFillColor(LIGHT)
            pdf.roundRect(cx, yy - 140, col_w, 140, 8, stroke=0, fill=1)
            pdf.setFillColor(TEAL if title in ("v2 tooling", "Next") else BLUE)
            pdf.setFont("Helvetica-Bold", 12)
            pdf.drawString(cx + 14, yy - 24, title)
            wrap(pdf, body, cx + 14, yy - 44, col_w - 28, 9.5, 12.5)
            yy -= 156
    footer(pdf, n)
    pdf.showPage()


def main():
    methods = load_methods()
    idx = run_index()
    spend = sum(e.get("cost_usd") or 0 for s in methods.values() for e in s.values())
    OUT.parent.mkdir(exist_ok=True)
    pdf = canvas.Canvas(str(OUT), pagesize=landscape(A4), pageCompression=1)
    pdf.setTitle("Lathe harness baseline report")
    cover(pdf, methods, spend)
    setup_page(pdf, 2)
    leaderboard(pdf, methods, 3)
    scatter_page(pdf, 4)
    n = 5
    for step in LADDER:
        n = ablation_pages(pdf, methods, idx, step, n)
    n = final_render_page(pdf, methods, idx, n)
    findings(pdf, n)
    pdf.save()
    print(f"wrote {OUT} ({n} content pages)")


if __name__ == "__main__":
    main()
